{{ config(
    materialized='table',
    schema='presentation'
) }}


WITH json_data AS (
  SELECT
    attributes::jsonb AS genericSMF_data
 FROM {{ source('sat_sec', 'sat_security') }}
)


  SELECT
    genericSMF_data -> 'genericSMF'  ->> 'sourceName' AS sourcename,
genericSMF_data -> 'genericSMF'  ->> 'updateSource' AS updatesource,
genericSMF_data -> 'genericSMF'  ->> 'effectiveDate' AS effectivedate,
genericSMF_data -> 'genericSMF'  ->> 'languageid' AS languageid,
genericSMF_data -> 'genericSMF'  ->> 'tagNochangecase' AS tagnochangecase,
genericSMF_data -> 'genericSMF'  ->> 'preserveNull' AS preservenull,
genericSMF_data -> 'genericSMF'  ->> 'noLoadValidationFlag' AS noloadvalidationflag,
genericSMF_data -> 'genericSMF'  ->> 'accountingValidationFlag' AS accountingvalidationflag,
genericSMF_data -> 'genericSMF'  ->> 'primaryAssetId' AS primaryassetid,
genericSMF_data -> 'genericSMF'  ->> 'primaryAssetType' AS primaryassettype,
genericSMF_data -> 'genericSMF'  ->> 'issueName' AS issuename,
genericSMF_data -> 'genericSMF'  ->> 'unicodeIssueName' AS unicodeissuename,
genericSMF_data -> 'genericSMF'  ->> 'issueDescription' AS issuedescription,
genericSMF_data -> 'genericSMF'  ->> 'ticker' AS ticker,
genericSMF_data -> 'genericSMF'  ->> 'cusip' AS cusip,
genericSMF_data -> 'genericSMF'  ->> 'cusippay' AS cusippay,
genericSMF_data -> 'genericSMF'  ->> 'cusipreceive' AS cusipreceive,
genericSMF_data -> 'genericSMF'  ->> 'isin' AS isin,
genericSMF_data -> 'genericSMF'  ->> 'sedol' AS sedol,
genericSMF_data -> 'genericSMF'  ->> 'reuters' AS reuters,
genericSMF_data -> 'genericSMF'  ->> 'bloombergid' AS bloombergid,
genericSMF_data -> 'genericSMF'  ->> 'sicovmid' AS sicovmid,
genericSMF_data -> 'genericSMF'  ->> 'valorenid' AS valorenid,
genericSMF_data -> 'genericSMF'  ->> 'cedel' AS cedel,
genericSMF_data -> 'genericSMF'  ->> 'internalid' AS internalid,
genericSMF_data -> 'genericSMF'  ->> 'cinsid' AS cinsid,
genericSMF_data -> 'genericSMF'  ->> '_989flag' AS _989flag,
genericSMF_data -> 'genericSMF'  ->> 'accrualmethod' AS accrualmethod,
genericSMF_data -> 'genericSMF'  ->> 'altassetid' AS altassetid,
genericSMF_data -> 'genericSMF'  ->> 'altassetidtype' AS altassetidtype,
genericSMF_data -> 'genericSMF'  ->> 'altsecuritytype' AS altsecuritytype,
genericSMF_data -> 'genericSMF'  ->> 'amortind' AS amortind,
genericSMF_data -> 'genericSMF'  ->> 'amortizationparvalue' AS amortizationparvalue,
genericSMF_data -> 'genericSMF'  ->> 'annualdividend' AS annualdividend,
genericSMF_data -> 'genericSMF'  ->> 'businessday' AS businessday,
genericSMF_data -> 'genericSMF'  ->> 'callable' AS callable,
genericSMF_data -> 'genericSMF'  ->> 'callputflag' AS callputflag,
genericSMF_data -> 'genericSMF'  ->> 'compoundflag' AS compoundflag,
genericSMF_data -> 'genericSMF'  ->> 'contractsize' AS contractsize,
genericSMF_data -> 'genericSMF'  ->> 'couponfreqcode' AS couponfreqcode,
genericSMF_data -> 'genericSMF'  ->> 'currencycode' AS currencycode,
genericSMF_data -> 'genericSMF'  ->> 'daytype' AS daytype,
genericSMF_data -> 'genericSMF'  ->> 'defaultthreshold' AS defaultthreshold,
genericSMF_data -> 'genericSMF'  ->> 'deflationprotectmaturity' AS deflationprotectmaturity,
genericSMF_data -> 'genericSMF'  ->> 'dlvcategory' AS dlvcategory,
genericSMF_data -> 'genericSMF'  ->> 'drdeligible' AS drdeligible,
genericSMF_data -> 'genericSMF'  ->> 'dualcurconvfactor' AS dualcurconvfactor,
genericSMF_data -> 'genericSMF'  ->> 'dualcurrencyindicator' AS dualcurrencyindicator,
genericSMF_data -> 'genericSMF'  ->> 'eventacceleration' AS eventacceleration,
genericSMF_data -> 'genericSMF'  ->> 'ficoupondayofmonth' AS ficoupondayofmonth,
genericSMF_data -> 'genericSMF'  ->> 'fidzerocpn' AS fidzerocpn,
genericSMF_data -> 'genericSMF'  ->> 'fiextaccrualperiod' AS fiextaccrualperiod,
genericSMF_data -> 'genericSMF'  ->> 'fiextbaseleveldate' AS fiextbaseleveldate,
genericSMF_data -> 'genericSMF'  ->> 'fiextcalltype' AS fiextcalltype,
genericSMF_data -> 'genericSMF'  ->> 'fiextconduit' AS fiextconduit,
genericSMF_data -> 'genericSMF'  ->> 'fiextconvertibleflag' AS fiextconvertibleflag,
genericSMF_data -> 'genericSMF'  ->> 'fiextcounty' AS fiextcounty,
genericSMF_data -> 'genericSMF'  ->> 'fiextcoupfreq' AS fiextcoupfreq,
genericSMF_data -> 'genericSMF'  ->> 'fiextdateconv' AS fiextdateconv,
genericSMF_data -> 'genericSMF'  ->> 'fiextdeal' AS fiextdeal,
genericSMF_data -> 'genericSMF'  ->> 'fiextdelayconv' AS fiextdelayconv,
genericSMF_data -> 'genericSMF'  ->> 'fiextembeddedoption' AS fiextembeddedoption,
genericSMF_data -> 'genericSMF'  ->> 'fiextendadjflag' AS fiextendadjflag,
genericSMF_data -> 'genericSMF'  ->> 'fiextfirstprindt' AS fiextfirstprindt,
genericSMF_data -> 'genericSMF'  ->> 'fiextfirstresetcappct' AS fiextfirstresetcappct,
genericSMF_data -> 'genericSMF'  ->> 'fiextfirstresetflavor' AS fiextfirstresetflavor,
genericSMF_data -> 'genericSMF'  ->> 'fiextfirstresfloorpct' AS fiextfirstresfloorpct,
genericSMF_data -> 'genericSMF'  ->> 'fiextgrossmargin' AS fiextgrossmargin,
genericSMF_data -> 'genericSMF'  ->> 'fiextindexresetterm' AS fiextindexresetterm,
genericSMF_data -> 'genericSMF'  ->> 'fiextindxlookback' AS fiextindxlookback,
genericSMF_data -> 'genericSMF'  ->> 'fiextmaxcallnotice' AS fiextmaxcallnotice,
genericSMF_data -> 'genericSMF'  ->> 'fiextmincallnotice' AS fiextmincallnotice,
genericSMF_data -> 'genericSMF'  ->> 'fiextminlotsize' AS fiextminlotsize,
genericSMF_data -> 'genericSMF'  ->> 'fiextmultiorigfl' AS fiextmultiorigfl,
genericSMF_data -> 'genericSMF'  ->> 'fiextmuniind' AS fiextmuniind,
genericSMF_data -> 'genericSMF'  ->> 'fiextmunipf' AS fiextmunipf,
genericSMF_data -> 'genericSMF'  ->> 'fiextnegamcap' AS fiextnegamcap,
genericSMF_data -> 'genericSMF'  ->> 'fiextoidprice' AS fiextoidprice,
genericSMF_data -> 'genericSMF'  ->> 'fiextoriglifecap' AS fiextoriglifecap,
genericSMF_data -> 'genericSMF'  ->> 'fiextoriglifefloor' AS fiextoriglifefloor,
genericSMF_data -> 'genericSMF'  ->> 'fiextorignetmargin' AS fiextorignetmargin,
genericSMF_data -> 'genericSMF'  ->> 'fiextorigterm' AS fiextorigterm,
genericSMF_data -> 'genericSMF'  ->> 'fiextpayincr' AS fiextpayincr,
genericSMF_data -> 'genericSMF'  ->> 'fiextprinceometh' AS fiextprinceometh,
genericSMF_data -> 'genericSMF'  ->> 'fiextpvschedopt' AS fiextpvschedopt,
genericSMF_data -> 'genericSMF'  ->> 'fiextregistr' AS fiextregistr,
genericSMF_data -> 'genericSMF'  ->> 'fiextremainlife' AS fiextremainlife,
genericSMF_data -> 'genericSMF'  ->> 'fiextscmincr' AS fiextscmincr,
genericSMF_data -> 'genericSMF'  ->> 'fiextseasonedaccr' AS fiextseasonedaccr,
genericSMF_data -> 'genericSMF'  ->> 'fiextsecref' AS fiextsecref,
genericSMF_data -> 'genericSMF'  ->> 'fiextsectype' AS fiextsectype,
genericSMF_data -> 'genericSMF'  ->> 'fiextspread' AS fiextspread,
genericSMF_data -> 'genericSMF'  ->> 'fiextstripdate' AS fiextstripdate,
genericSMF_data -> 'genericSMF'  ->> 'fiextstripflag' AS fiextstripflag,
genericSMF_data -> 'genericSMF'  ->> 'fiextstripfirstcpn' AS fiextstripfirstcpn,
genericSMF_data -> 'genericSMF'  ->> 'fiextstriporigcpn' AS fiextstriporigcpn,
genericSMF_data -> 'genericSMF'  ->> 'fiextsupportid' AS fiextsupportid,
genericSMF_data -> 'genericSMF'  ->> 'fiextsupporttype' AS fiextsupporttype,
genericSMF_data -> 'genericSMF'  ->> 'fiexttradeaccrual' AS fiexttradeaccrual,
genericSMF_data -> 'genericSMF'  ->> 'fiextusmodel' AS fiextusmodel,
genericSMF_data -> 'genericSMF'  ->> 'fiextwtavgmat' AS fiextwtavgmat,
genericSMF_data -> 'genericSMF'  ->> 'fifxdresetdate' AS fifxdresetdate,
genericSMF_data -> 'genericSMF'  ->> 'fiispostrefund' AS fiispostrefund,
genericSMF_data -> 'genericSMF'  ->> 'fixdmatpaymentflag' AS fixdmatpaymentflag,
genericSMF_data -> 'genericSMF'  ->> 'floatingbasecode' AS floatingbasecode,
genericSMF_data -> 'genericSMF'  ->> 'floor' AS floor,
genericSMF_data -> 'genericSMF'  ->> 'frequency' AS frequency,
genericSMF_data -> 'genericSMF'  ->> 'guarenteed' AS guarenteed,
genericSMF_data -> 'genericSMF'  ->> 'identifers' AS identifers,
genericSMF_data -> 'genericSMF'  ->> 'issuecountry' AS issuecountry,
genericSMF_data -> 'genericSMF'  ->> 'issuercountrycode' AS issuercountrycode,
genericSMF_data -> 'genericSMF'  ->> 'issuerid' AS issuerid,
genericSMF_data -> 'genericSMF'  ->> 'issuerlongname' AS issuerlongname,
genericSMF_data -> 'genericSMF'  ->> 'isshort' AS isshort,
genericSMF_data -> 'genericSMF'  ->> 'issueid' AS issueid,
genericSMF_data -> 'genericSMF'  ->> 'issubord' AS issubord,
genericSMF_data -> 'genericSMF'  ->> 'listdate' AS listdate,
genericSMF_data -> 'genericSMF'  ->> 'minsubmult' AS minsubmult,
genericSMF_data -> 'genericSMF'  ->> 'mnemonic' AS mnemonic,
genericSMF_data -> 'genericSMF'  ->> 'multifixflag' AS multifixflag,
genericSMF_data -> 'genericSMF'  ->> 'multiplyby100' AS multiplyby100,
genericSMF_data -> 'genericSMF'  ->> 'namechangedate' AS namechangedate,
genericSMF_data -> 'genericSMF'  ->> 'namechangeflag' AS namechangeflag,
genericSMF_data -> 'genericSMF'  ->> 'othertypes' AS othertypes,
genericSMF_data -> 'genericSMF'  ->> 'primarycurrency' AS primarycurrency,
genericSMF_data -> 'genericSMF'  ->> 'primaryexchange' AS primaryexchange,
genericSMF_data -> 'genericSMF'  ->> 'putable' AS putable,
genericSMF_data -> 'genericSMF'  ->> 'reinvestmentmethod' AS reinvestmentmethod,
genericSMF_data -> 'genericSMF'  ->> 'securitydescription' AS securitydescription,
genericSMF_data -> 'genericSMF'  ->> 'shortdescription' AS shortdescription,
genericSMF_data -> 'genericSMF'  ->> 'specificdayofmonth' AS specificdayofmonth,
genericSMF_data -> 'genericSMF'  ->> 'spread' AS spread,
genericSMF_data -> 'genericSMF'  ->> 'stateprovince' AS stateprovince,
genericSMF_data -> 'genericSMF'  ->> 'tickerticker' AS tickerticker,
genericSMF_data -> 'genericSMF'  ->> 'timezone' AS timezone,
genericSMF_data -> 'genericSMF'  ->> 'tradingfactor' AS tradingfactor,
genericSMF_data -> 'genericSMF'  ->> 'underlyingassetid' AS underlyingassetid,
genericSMF_data -> 'genericSMF'  ->> 'underlyingtype' AS underlyingtype,
genericSMF_data -> 'genericSMF'  ->> 'units' AS units,
genericSMF_data -> 'genericSMF'  ->> 'utcconversionflag' AS utcconversionflag,
genericSMF_data -> 'genericSMF'  ->> 'valuemultiplier' AS valuemultiplier,
genericSMF_data -> 'genericSMF'  ->> 'valuationmethod' AS valuationmethod,
genericSMF_data -> 'genericSMF'  ->> 'votingright' AS votingright,
genericSMF_data -> 'genericSMF'  ->> 'warrant' AS warrant,
genericSMF_data -> 'genericSMF'  ->> 'withholdingtax' AS withholdingtax,
genericSMF_data -> 'genericSMF'  ->> 'xtfcode' AS xtfcode,
genericSMF_data -> 'genericSMF'  ->> 'yesno' AS yesno

  FROM json_data